# Generated by Django 5.2.12 on 2026-03-21 09:33

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('due_date', models.DateField(verbose_name='Muddat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Muddat',
                'verbose_name_plural': 'Muddatlar',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('info', "Ma'lumot"), ('deadline', 'Muddat'), ('rating', 'Reyting')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='scientificwork',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='scientificwork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='works/', validators=[app.models.validate_file_extension, app.models.validate_file_size], verbose_name='Fayl (PDF)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('katta_oqituvchi', "Katta o'qituvchi"), ('oqituvchi', "O'qituvchi")], default='oqituvchi', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('work_added', "Ish qo'shildi"), ('work_edited', 'Ish tahrirlandi'), ('work_deleted', "Ish o'chirildi"), ('work_approved', 'Ish tasdiqlandi'), ('work_rejected', 'Ish rad etildi'), ('profile_updated', 'Profil yangilandi'), ('login', 'Tizimga kirdi'), ('score_changed', "Ball o'zgartirildi")], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faoliyat tarixi',
                'verbose_name_plural': 'Faoliyat tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
